apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: telegraf
  template:
    metadata:
      labels:
        name: telegraf
    spec:
      serviceAccountName: telegraf-account
      containers:
      - name: telegraf
        image: telegraf:alpine
        env:
        - name: HOSTNAME
          value: "telegraf-polling-service"
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
      volumes:
      - name: config
        configMap:
          name: telegraf-config