apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ft_services
spec:
  ports:
  - port: 21
    name: ftps
  - port: 15477
    name: ftps-data
  selector:
    app: ft_services
    tier: ftps
  type: LoadBalancer
